PROJECT_SOURCE_CODE_PATH="/path/to/source"
PROJECT_JAR_PATH="/path/to/jar/project.jar"
PROJECT_PACKAGE_NAME="com.example.app"
THEO_STATIC_ANALYZER_JAR_PATH="/path/to/theo-static-analyzer.jar"
THEO_DYNAMIC_ANALYZER_JAR_PATH="/path/to/theo-dynamic-analyzer.jar"
JFR_SETTINGS_FILE_PATH="/path/to/jfr-settings.jfc"
JFR_REPORT_PATH="/path/to/jfr-recording.jfr"
THEO_JAVA_AGENT_JAR_PATH="/path/to/theo-java-agent.jar"
PACKAGE_MAP_OUTPUT_PATH="/path/to/output-package-map.txt"
NOISE_REMOVAL="true"
WRITE_DIFF_TO_FILE="true"
MAIN_CLASS="org.example.app.Main"
MAIN_CLASS_PARAMS="arg1 arg2 arg3"
MODE="test"  # or "prod"