PROJECT_ROOT_DIR="/Users/yogyagamage/Documents/KTH/theo/prod/graphhopper-new"
PROJECT_SOURCE_CODE_PATH="/Users/yogyagamage/Documents/KTH/theo/prod/graphhopper-new/web"
PROJECT_JAR_PATH="/Users/yogyagamage/Documents/KTH/theo/prod/graphhopper-new/web/target/graphhopper-web-11.0-SNAPSHOT.jar"
PROJECT_PACKAGE_NAME="com.graphhopper.application"
THEO_STATIC_ANALYZER_JAR_PATH="/Users/yogyagamage/Documents/UdeM/theo/theo-static/target/theo-static-1.0-SNAPSHOT-jar-with-dependencies.jar"
THEO_DYNAMIC_ANALYZER_JAR_PATH="/Users/yogyagamage/Documents/UdeM/theo/theo-test-exec/target/theo-test-exec-1.0-SNAPSHOT-jar-with-dependencies.jar"
JFR_SETTINGS_FILE_PATH="/Users/yogyagamage/Documents/UdeM/theo/settings.jfc"
JFR_REPORT_PATH="/Users/yogyagamage/Documents/KTH/theo/prod/graphhopper-new/web/jfr-report1.jfr"
THEO_JAVA_AGENT_JAR_PATH="/Users/yogyagamage/Documents/UdeM/theo/theo-agent/target/theo-agent-1.0-SNAPSHOT-jar-with-dependencies.jar"
PACKAGE_MAP_OUTPUT_PATH="/Users/yogyagamage/Documents/KTH/theo/prod/graphhopper-new/web/package-map.json"
NOISE_REMOVAL="false"
WRITE_DIFF_TO_FILE="true"
MAIN_CLASS="com.graphhopper.application.GraphHopperApplication"
MAIN_CLASS_PARAMS=""
MODE="prod"  # or "prod"
E2E_PATH="/Users/yogyagamage/Documents/UdeM/theo/e2e.py"
ANALYSIS_SCRIPT="/Users/yogyagamage/Documents/UdeM/theo/run-theo-analysis.sh"
REPORTS_DIR="/Users/yogyagamage/Documents/UdeM/theo-reports/all-auto"